import Dexie, { type Table } from 'dexie';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

/**
 * Interface representing a saved newspaper clipping in Dexie.js
 */
export interface ClippingRecord {
  id?: number;
  template: string;
  newspaperName: string;
  tagline?: string;
  date: string;
  headline: string;
  story: string;
  base64Image?: string | null;
  photoCaption?: string;
  timestamp: number;
}

/**
 * Dexie.js Database Class
 */
export class NewspaperDatabase extends Dexie {
  clippingHistory!: Table<ClippingRecord, number>;

  constructor() {
    super('NewspaperAppDB');
    this.version(1).stores({
      clippingHistory: '++id, template, headline, timestamp',
    });
  }
}

// Export singleton database instance
export const db = new NewspaperDatabase();

/**
 * 3. Save current editor state to Dexie.js
 */
export async function saveToDrafts(
  data: Omit<ClippingRecord, 'id' | 'timestamp'> & { thumbnail?: string | null }
): Promise<number> {
  const id = await db.clippingHistory.add({
    template: data.template,
    newspaperName: data.newspaperName,
    tagline: data.tagline,
    date: data.date,
    headline: data.headline,
    story: data.story,
    base64Image: data.thumbnail || data.base64Image || null,
    photoCaption: data.photoCaption,
    timestamp: Date.now(),
  });
  return id;
}

/**
 * Fetch all clippings ordered by most recent first
 */
export async function getRecentClippings(limit = 50): Promise<ClippingRecord[]> {
  return await db.clippingHistory.orderBy('timestamp').reverse().limit(limit).toArray();
}

/**
 * Delete a single clipping by ID
 */
export async function deleteClipping(id: number): Promise<void> {
  await db.clippingHistory.delete(id);
}

/**
 * Clear all clipping history
 */
export async function clearAllClippings(): Promise<void> {
  await db.clippingHistory.clear();
}

/**
 * Capture element as lightweight thumbnail for storage
 */
export async function captureThumbnail(element: HTMLElement): Promise<string> {
  try {
    const canvas = await html2canvas(element, {
      scale: 0.6,
      useCORS: true,
      allowTaint: true,
      logging: false,
    });
    return canvas.toDataURL('image/jpeg', 0.65);
  } catch {
    return '';
  }
}

// =========================================================================
// 1. EXPORT ENGINE: Functions targeting the PreviewPanel <div>
// =========================================================================

function triggerDownload(url: string, filename: string) {
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

/**
 * Render HTMLElement to high-resolution canvas
 */
async function renderElementCanvas(element: HTMLElement, scale = 2): Promise<HTMLCanvasElement> {
  return await html2canvas(element, {
    scale,
    useCORS: true,
    allowTaint: true,
    backgroundColor: null,
    logging: false,
    windowWidth: element.scrollWidth,
    windowHeight: element.scrollHeight,
  });
}

/**
 * Export PreviewPanel as PNG
 */
export async function downloadAsPNG(
  element: HTMLElement,
  filename = 'vintage-newspaper-clipping.png'
): Promise<void> {
  const canvas = await renderElementCanvas(element, 2);
  const dataUrl = canvas.toDataURL('image/png');
  triggerDownload(dataUrl, filename);
}

/**
 * Export PreviewPanel as JPG
 */
export async function downloadAsJPG(
  element: HTMLElement,
  filename = 'vintage-newspaper-clipping.jpg',
  quality = 0.95
): Promise<void> {
  const canvas = await renderElementCanvas(element, 2);
  const dataUrl = canvas.toDataURL('image/jpeg', quality);
  triggerDownload(dataUrl, filename);
}

/**
 * Export PreviewPanel as SVG
 */
export async function downloadAsSVG(
  element: HTMLElement,
  filename = 'vintage-newspaper-clipping.svg'
): Promise<void> {
  const canvas = await renderElementCanvas(element, 2);
  const dataUrl = canvas.toDataURL('image/png');
  const width = element.offsetWidth || 800;
  const height = element.offsetHeight || 1000;

  const svgContent = `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">
  <title>Newspaper Clipping</title>
  <desc>Generated by The Vintage Press</desc>
  <image width="${width}" height="${height}" xlink:href="${dataUrl}"/>
</svg>`;

  const blob = new Blob([svgContent], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  triggerDownload(url, filename);
  URL.revokeObjectURL(url);
}

/**
 * Export PreviewPanel as PDF (jsPDF)
 */
export async function downloadAsPDF(
  element: HTMLElement,
  filename = 'vintage-newspaper-clipping.pdf'
): Promise<void> {
  const canvas = await renderElementCanvas(element, 2);
  const imgData = canvas.toDataURL('image/jpeg', 0.95);

  const imgWidth = canvas.width;
  const imgHeight = canvas.height;

  // Determine orientation based on aspect ratio
  const orientation = imgWidth > imgHeight ? 'landscape' : 'portrait';

  const pdf = new jsPDF({
    orientation,
    unit: 'px',
    format: [imgWidth, imgHeight],
  });

  pdf.addImage(imgData, 'JPEG', 0, 0, imgWidth, imgHeight);
  pdf.save(filename);
}
